#!/usr/bin/env bash
set -euo pipefail

if [ -z "$PROJECT" ]; then
  echo "Missing PROJECT"
  exit 1
fi
if ! [[ "$PROJECT" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$ ]]; then
  echo "Invalid repository name"
  exit 1
fi
test -d generated-project
test -n "$(find generated-project -type f -print -quit)"

owner="$(gh api user --jq .login)"
candidate="$PROJECT"
n=2
while gh repo view "$owner/$candidate" >/dev/null 2>&1; do
  candidate="$PROJECT-$n"
  n=$((n+1))
done


if [[ "$PLATFORM" =~ (Web|PWA) ]]; then
  cat > generated-project/.github-pages.yml <<'EOF'
name: CodePilot2 Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
EOF
  mkdir -p generated-project/.github/workflows
  mv generated-project/.github-pages.yml generated-project/.github/workflows/deploy-pages.yml
fi

cd generated-project
git init
touch .nojekyll
git config user.name "CodePilot"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -b main
git add .
git commit -m "CodePilot: initial project"
gh repo create "$owner/$candidate" --public --description "Generated by CodePilot2" --source . --remote origin --push
cd ..
printf "https://github.com/%s/%s
" "$owner" "$candidate" > target-repo.txt

if [[ "$PLATFORM" =~ (Web|PWA) ]]; then
  printf "https://%s.github.io/%s/
" "$owner" "$candidate" > pages-url.txt
fi

echo "Repository: https://github.com/$owner/$candidate"
