#!/usr/bin/env bash
set -euo pipefail

if [ -z "$PROJECT" ]; then
  echo "Missing PROJECT"
  exit 1
fi
if ! [[ "$PROJECT" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$ ]]; then
  echo "Invalid repository name"
  exit 1
fi
test -d generated-project
test -n "$(find generated-project -type f -print -quit)"

owner="$(gh api user --jq .login)"
candidate="$PROJECT"
n=2
while gh repo view "$owner/$candidate" >/dev/null 2>&1; do
  candidate="$PROJECT-$n"
  n=$((n+1))
done


cd generated-project
git init
touch .nojekyll
git config user.name "CodePilot"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -b main
git add .
git commit -m "CodePilot: initial project"
gh repo create "$owner/$candidate" --public --description "Generated by CodePilot2" --source . --remote origin --push
cd ..
printf "https://github.com/%s/%s
" "$owner" "$candidate" > target-repo.txt

if [[ "$PLATFORM" =~ (Web|PWA) ]]; then
  gh api --method POST "repos/$owner/$candidate/pages"     -f build_type=workflow -f "source[branch]=main" -f "source[path]=/"     >/dev/null 2>&1 || true
  printf "https://%s.github.io/%s/
" "$owner" "$candidate" > pages-url.txt
fi

echo "Repository: https://github.com/$owner/$candidate"
